from __future__ import annotations

from typing import Optional

from consensusd.models import Evidence, Proposal, Review, ReviewDecision, ReviewStatus, Run


def _diff_stat(evidence: list[Evidence]) -> str:
    for item in evidence:
        if item.kind == "git_diff_stat":
            text = item.output.strip()
            return text if text else "(empty git diff --stat)"
    return "(git diff --stat was not captured)"


class MockCodexRunner:
    def generate_proposal(self, run: Run, prior_review: Optional[Review], evidence: list[Evidence]) -> str:
        diff_stat = _diff_stat(evidence)
        if run.current_round == 1:
            return (
                "# MOCK Codex Proposal Round 1\n\n"
                "**Runner mode:** mock. This is a deterministic transport/state-machine rehearsal, "
                "not a real Codex review of repository semantics.\n\n"
                "<!-- CONSENSUSD:DRAFT_PRD_START -->\n"
                f"# Draft PRD - Mock Review {run.run_id[-8:]}\n\n"
                "## Problem\n"
                "The daemon needs a concrete first-round planning artifact so Kimi reviews a draft PRD and test spec, "
                "not only a narrative proposal. This mock draft proves the artifact contract while staying blocked for production use.\n\n"
                "## Goals\n"
                "- Exercise draft PRD/test-spec generation before Kimi review.\n"
                "- Keep Ralph handoff approval-gated and blocked for mock output.\n"
                "- Surface missing safety evidence as reviewable acceptance criteria.\n\n"
                "## Non-Goals\n"
                "- Do not approve real implementation.\n"
                "- Do not validate repository semantics.\n"
                "- Do not launch Ralph.\n\n"
                "## Requirements\n"
                "- Proposal must contain draft PRD and draft test spec markers.\n"
                "- Kimi must review the concrete draft bundle.\n"
                "- Missing approval-phrase and foreign-host checks remain explicit blockers.\n\n"
                "## Acceptance Criteria\n"
                "- Draft artifacts are written before Kimi review.\n"
                "- Draft quality evidence is recorded in SQLite.\n"
                "- The mock handoff remains blocked even if the workflow reaches approval gate.\n"
                "<!-- CONSENSUSD:DRAFT_PRD_END -->\n\n"
                "<!-- CONSENSUSD:DRAFT_TEST_SPEC_START -->\n"
                f"# Draft Test Spec - Mock Review {run.run_id[-8:]}\n\n"
                "## Test Matrix\n"
                "| Case | Expected |\n"
                "| --- | --- |\n"
                "| Draft markers | PRD and test spec are present |\n"
                "| Kimi round 1 | reviews concrete draft bundle |\n"
                "| Mock handoff | stays blocked |\n\n"
                "## Negative Tests\n"
                "- Missing draft PRD marker should fail draft quality.\n"
                "- Missing draft test spec marker should fail draft quality.\n"
                "- Mock output must not produce a production Ralph prompt.\n\n"
                "## Commands\n"
                "- `uv run pytest`\n"
                "- `uv run consensusd review ... --runner-mode mock`\n\n"
                "## Evidence Capture\n"
                "- Record proposal_draft_artifact_bundle evidence.\n"
                "- Record proposal_draft_quality evidence.\n"
                "- Capture Kimi critique and final brief blockers.\n\n"
                "## Pass / Fail Gates\n"
                "Pass when draft artifacts exist before review and mock handoff remains blocked. "
                "Fail if Kimi is only reviewing a thin prose plan or if Ralph is authorized.\n"
                "<!-- CONSENSUSD:DRAFT_TEST_SPEC_END -->\n\n"
                f"Objective: {run.objective}\n\n"
                f"Project: `{run.project_root}`\n\n"
                "## Captured Repository Evidence\n"
                "```text\n"
                f"{diff_stat}\n"
                "```\n\n"
                "## Draft Review Plan\n"
                "- Treat the supplied Ralph completion summary as a claim set, not proof.\n"
                "- Check the changed files and safety gates before any Ralph handoff.\n"
                "- Keep the handoff approval-gated.\n\n"
                "Known mock gap: this draft does not yet require proof that the approval phrase "
                "and endpoint host validation reject unsafe inputs."
            )
        critique = prior_review.content if prior_review else "No prior critique."
        return (
            "# MOCK Codex Proposal Round 2\n\n"
            "**Runner mode:** mock. This revision only proves the consensus loop shape.\n\n"
            "<!-- CONSENSUSD:DRAFT_PRD_START -->\n"
            f"# Draft PRD - Mock Review Revision {run.run_id[-8:]}\n\n"
            "## Problem\n"
            "Round 2 must demonstrate that Codex can revise the PRD/test-spec bundle after Kimi critique rather than "
            "answering with prose alone. The mock revision locks the evidence gates Kimi requested.\n\n"
            "## Goals\n"
            "- Address Kimi's approval-phrase and foreign-host evidence requests.\n"
            "- Preserve mock-only handoff blocking.\n"
            "- Keep the draft bundle concrete enough for review.\n\n"
            "## Non-Goals\n"
            "- No real P11B approval.\n"
            "- No Ralph execution.\n"
            "- No credential or network work.\n\n"
            "## Requirements\n"
            "- Require evidence that missing approval phrases are rejected.\n"
            "- Require evidence that foreign-host URLs are rejected.\n"
            "- Require targeted guard tests before any real handoff.\n\n"
            "## Acceptance Criteria\n"
            "- Kimi items are mapped to draft PRD and test-spec changes.\n"
            "- Final mock OMX remains blocked for production Ralph handoff.\n"
            "- Draft quality evidence passes before review.\n"
            "<!-- CONSENSUSD:DRAFT_PRD_END -->\n\n"
            "<!-- CONSENSUSD:DRAFT_TEST_SPEC_START -->\n"
            f"# Draft Test Spec - Mock Review Revision {run.run_id[-8:]}\n\n"
            "## Test Matrix\n"
            "| Case | Expected |\n"
            "| --- | --- |\n"
            "| Missing approval phrase | rejected |\n"
            "| Wrong approval phrase | rejected |\n"
            "| Foreign host URL | rejected |\n"
            "| Mock Ralph prompt | not shown |\n\n"
            "## Negative Tests\n"
            "- Do not accept plans without approval-phrase rejection evidence.\n"
            "- Do not accept plans without foreign-host rejection evidence.\n"
            "- Do not treat mock approval as production approval.\n\n"
            "## Commands\n"
            "- `uv run pytest`\n"
            "- Targeted guard tests named by the real project when available.\n\n"
            "## Evidence Capture\n"
            "- Capture changed draft artifacts.\n"
            "- Capture Kimi approval and remaining reservations.\n"
            "- Capture Ralph blocked readiness.\n\n"
            "## Pass / Fail Gates\n"
            "Pass only if the revised draft bundle addresses the Kimi critique and remains safely blocked. "
            "Fail if the final brief implies real implementation approval.\n"
            "<!-- CONSENSUSD:DRAFT_TEST_SPEC_END -->\n\n"
            f"Objective: {run.objective}\n\n"
            f"Project: `{run.project_root}`\n\n"
            "## Captured Repository Evidence\n"
            "```text\n"
            f"{diff_stat}\n"
            "```\n\n"
            "## Revised Review Plan\n"
            "- Block Ralph handoff unless approval-phrase validation rejects missing or wrong phrases.\n"
            "- Block Ralph handoff unless URL/host validation rejects non-Revolut hosts instead of normalizing them.\n"
            "- Require targeted tests for the collector guard and skeleton before treating P11B as ready.\n"
            "- Preserve the human approval gate before any Ralph continuation.\n\n"
            f"Addressed Kimi critique:\n{critique}"
        )

    def review_proposal(self, run: Run, proposal: Proposal, evidence: list[Evidence]) -> ReviewDecision:
        raise NotImplementedError("Codex runner does not review proposals")

    def generate_omx(self, run: Run, consensus_proposal: Proposal, evidence: list[Evidence]) -> str:
        return (
            "<!-- CONSENSUSD:PRD_START -->\n"
            f"# PRD - Mock Consensus Review {run.run_id[-8:]}\n\n"
            "## Problem\n"
            "Exercise consensusd's durable review workflow without claiming real implementation approval. "
            "The mock run proves the same artifact contract that real Codex/Kimi runs use: durable state, "
            "auditable negotiation, separate planning files, and a visible pause gate before any Ralph handoff.\n\n"
            "## Goals\n"
            "- Prove proposal, Kimi review, revision, OMX, PRD, and test-spec artifact plumbing.\n"
            "- Keep Ralph handoff blocked for mock output.\n\n"
            "## Non-Goals\n"
            "- Do not validate production P11B correctness.\n"
            "- Do not authorize Ralph implementation.\n\n"
            "## Requirements\n"
            "- Persist a separate PRD artifact for every completed mock run.\n"
            "- Persist a separate test-spec artifact for every completed mock run.\n"
            "- Record the artifact bundle in SQLite evidence.\n"
            "- Mark the mock plan as blocked for production Ralph handoff.\n\n"
            "## Acceptance Criteria\n"
            "- A mock run reaches `AWAITING_HUMAN_APPROVAL`.\n"
            "- PRD and test-spec artifact paths are recorded in the brief.\n"
            "- Ralph handoff is blocked because the runner is mock.\n"
            "- The final brief names why the handoff is blocked instead of printing a production `$ralph` prompt.\n"
            "- The SQLite event/evidence log records both the artifact bundle and the artifact quality result.\n\n"
            "## Risks\n"
            "- A mock approval can look deceptively similar to a real review if the brief omits runner mode.\n"
            "- Thin PRD/test-spec output can make the harness appear healthier than it is.\n"
            "- Future changes must keep mock output explicitly blocked for production Ralph handoff.\n"
            "<!-- CONSENSUSD:PRD_END -->\n\n"
            "<!-- CONSENSUSD:TEST_SPEC_START -->\n"
            f"# Test Spec - Mock Consensus Review {run.run_id[-8:]}\n\n"
            "## Test Matrix\n"
            "| Case | Expected |\n"
            "| --- | --- |\n"
            "| Mock full run | reaches approval gate |\n"
            "| Round 1 critique | requests revision |\n"
            "| Round 2 critique | approves mock workflow only |\n"
            "| Handoff readiness | blocks Ralph prompt |\n\n"
            "## Commands\n"
            "- `uv run pytest`\n"
            "- `uv run consensusd review ... --runner-mode mock`\n"
            "\n## Evidence Capture\n"
            "- Capture the final run status.\n"
            "- Capture PRD/test-spec/OMX/context-bridge paths.\n"
            "- Capture Ralph handoff readiness and blockers.\n\n"
            "## Negative Tests\n"
            "- Do not present a production `$ralph` prompt for mock output.\n"
            "- Do not treat mock approval as production implementation approval.\n\n"
            "## Required Assertions\n"
            "- The PRD file contains goals, non-goals, requirements, acceptance criteria, and risks.\n"
            "- The test spec contains a matrix, negative tests, commands, evidence capture, and pass/fail gates.\n"
            "- The brief exposes artifact paths and quality status to Codex CLI users.\n"
            "- Mock handoff stays blocked even when Kimi returns approved for workflow purposes.\n\n"
            "## Pass / Fail Gates\n"
            "Pass only if the run reaches the approval gate, the artifact bundle exists, "
            "and mock Ralph handoff remains blocked. Fail if any artifact is missing or "
            "the brief presents a production `$ralph` prompt for mock output.\n"
            "<!-- CONSENSUSD:TEST_SPEC_END -->\n\n"
            "# MOCK OMX Implementation Plan\n\n"
            "> This plan was produced by deterministic mock runners. It is useful for testing "
            "MCP transport, SQLite durability, event ordering, and approval gating. It is not a "
            "real Codex/Kimi review verdict.\n\n"
            f"Run: `{run.run_id}`\n\n"
            f"Objective: {run.objective}\n\n"
            f"Project: `{run.project_root}`\n\n"
            "## Captured Repository Evidence\n"
            "```text\n"
            f"{_diff_stat(evidence)}\n"
            "```\n\n"
            "## Acceptance Criteria\n"
            "- Treat this run as a mock harness result only.\n"
            "- Before real Ralph handoff, use real Codex/Kimi runners or manual review evidence.\n"
            "- Verify approval-phrase rejection and foreign-host rejection in P11B guard tests.\n"
            "- Keep Ralph handoff approval-gated.\n\n"
            "## Work Plan\n"
            "1. Inspect the P11B guard and collector skeleton changes.\n"
            "2. Add or verify tests for missing approval phrases, wrong approval phrases, and foreign host URLs.\n"
            "3. Re-run the targeted Node tests plus syntax checks.\n"
            "4. Only then consider a real Ralph handoff.\n\n"
            "## Verification\n"
            "- This mock run verified the consensusd workflow plumbing.\n"
            "- It did not verify P11B implementation correctness.\n\n"
            "## Ralph Handoff Packet\n"
            "Do not pass this mock plan to Ralph as a production implementation plan."
        )


class MockKimiRunner:
    def generate_proposal(self, run: Run, prior_review: Optional[Review], evidence: list[Evidence]) -> str:
        raise NotImplementedError("Kimi runner does not generate proposals")

    def review_proposal(self, run: Run, proposal: Proposal, evidence: list[Evidence]) -> ReviewDecision:
        if proposal.round == 1:
            return ReviewDecision(
                status=ReviewStatus.NEEDS_REVISION,
                content=(
                    "Mock Kimi requires revision: before any real Ralph handoff, the plan must demand "
                    "evidence that missing approval phrases are rejected and foreign-host URLs are rejected. "
                    "Evidence expected: git diff --stat, targeted guard tests, and explicit P11B safety notes."
                ),
            )
        return ReviewDecision(
            status=ReviewStatus.APPROVED,
            content=(
                "Approved for mock workflow purposes only. The revised proposal names the critical P11B "
                "evidence gates, but a real Codex/Kimi runner must perform the substantive review."
            ),
        )

    def generate_omx(self, run: Run, consensus_proposal: Proposal, evidence: list[Evidence]) -> str:
        raise NotImplementedError("Kimi runner does not generate OMX plans")
