from __future__ import annotations

import os
import json
import re
import signal
import subprocess
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from .base import current_cancel_check, RunnerCancelled


@dataclass(frozen=True)
class CommandResult:
    stdout: str
    stderr: str
    returncode: int
    pid: int
    live_log_path: str | None = None


UUID_RE = r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"


def phase_artifact_dir(project_root: str | Path, run_id: str) -> Path:
    return Path(project_root) / ".consensusd" / "logs" / "runs" / run_id


def phase_artifact_paths(project_root: str | Path, run_id: str, phase: str, round_number: int) -> dict[str, Path]:
    safe_phase = phase.replace(".", "-").replace("_", "-")
    directory = phase_artifact_dir(project_root, run_id)
    stem = f"{safe_phase}-round-{round_number}"
    return {
        "live_log": directory / f"{stem}.live.log",
        "last_message": directory / f"{stem}.last-message.md",
    }


def extract_codex_thread_id(text: str) -> str | None:
    """Extract a resumable Codex thread id from `codex exec --json` output."""
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("{"):
            continue
        try:
            event = json.loads(stripped)
        except json.JSONDecodeError:
            continue
        found = _find_json_key(event, "thread_id")
        if isinstance(found, str) and re.fullmatch(UUID_RE, found):
            return found
    match = re.search(rf'"thread_id"\s*:\s*"({UUID_RE})"', text)
    return match.group(1) if match else None


def extract_kimi_session_id(text: str) -> str | None:
    """Extract the Kimi `-r` resume id printed by the CLI."""
    match = re.search(rf"To resume this session:\s*kimi\s+-r\s+({UUID_RE})", text)
    if match:
        return match.group(1)
    match = re.search(rf"(?:--session|--resume|-S|-r)\s+({UUID_RE})", text)
    return match.group(1) if match else None


def combined_result_text(result: CommandResult) -> str:
    parts = [result.stdout or "", result.stderr or ""]
    if result.live_log_path:
        try:
            parts.append(Path(result.live_log_path).read_text(encoding="utf-8", errors="replace"))
        except OSError:
            pass
    return "\n".join(parts)


def _find_json_key(value, key: str):
    if isinstance(value, dict):
        if key in value:
            return value[key]
        for item in value.values():
            found = _find_json_key(item, key)
            if found is not None:
                return found
    if isinstance(value, list):
        for item in value:
            found = _find_json_key(item, key)
            if found is not None:
                return found
    return None


def run_cancellable_command(
    command: Sequence[str],
    cwd: str | Path,
    timeout_sec: int,
    label: str,
    poll_interval: float = 0.25,
    live_log_path: str | Path | None = None,
) -> CommandResult:
    """Run a CLI subprocess and terminate its process group on cancellation.

    Production note: this is intentionally command-list based. consensusd never
    exposes arbitrary shell execution to agents; callers provide fixed runner
    commands from settings and prompts generated by the orchestrator.
    """

    live_log = Path(live_log_path) if live_log_path else None
    if live_log:
        live_log.parent.mkdir(parents=True, exist_ok=True)
        live_log.write_text(
            f"# consensusd live subprocess log\n"
            f"started_at={datetime.now(timezone.utc).isoformat()}\n"
            f"label={label}\n\n"
        )

    process = subprocess.Popen(
        list(command),
        cwd=str(cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
    )
    print(
        f"[consensusd] {label} pid={process.pid}"
        + (f" live_log={live_log}" if live_log else ""),
        flush=True,
    )
    deadline = None if timeout_sec <= 0 else time.monotonic() + timeout_sec
    cancel_check = current_cancel_check()
    stdout_chunks: list[str] = []
    stderr_chunks: list[str] = []
    reader_threads = [
        threading.Thread(
            target=_read_stream,
            args=(process.stdout, stdout_chunks, "stdout", live_log),
            daemon=True,
        ),
        threading.Thread(
            target=_read_stream,
            args=(process.stderr, stderr_chunks, "stderr", live_log),
            daemon=True,
        ),
    ]
    for thread in reader_threads:
        thread.start()

    while process.poll() is None:
        if cancel_check and cancel_check():
            _terminate_process_group(process)
            stdout, stderr = _finish_process(process, reader_threads, stdout_chunks, stderr_chunks)
            raise RunnerCancelled(
                f"{label} cancelled; terminated pid={process.pid}; "
                f"stdout_tail={stdout[-1000:]!r}; stderr_tail={stderr[-1000:]!r}"
            )
        if deadline is not None and time.monotonic() >= deadline:
            _terminate_process_group(process)
            stdout, stderr = _finish_process(process, reader_threads, stdout_chunks, stderr_chunks)
            raise TimeoutError(
                f"{label} timed out after {timeout_sec}s; pid={process.pid}; "
                f"stdout_tail={stdout[-1000:]!r}; stderr_tail={stderr[-1000:]!r}"
            )
        time.sleep(poll_interval)

    stdout, stderr = _finish_process(process, reader_threads, stdout_chunks, stderr_chunks)
    return CommandResult(
        stdout=stdout,
        stderr=stderr,
        returncode=process.returncode,
        pid=process.pid,
        live_log_path=str(live_log) if live_log else None,
    )


def _read_stream(stream, chunks: list[str], stream_name: str, live_log: Path | None) -> None:
    if stream is None:
        return
    try:
        for line in stream:
            chunks.append(line)
            if live_log:
                with live_log.open("a", encoding="utf-8", errors="replace") as handle:
                    handle.write(f"[{stream_name}] {line}")
                    handle.flush()
    finally:
        try:
            stream.close()
        except OSError:
            pass


def _finish_process(
    process: subprocess.Popen[str],
    reader_threads: list[threading.Thread],
    stdout_chunks: list[str],
    stderr_chunks: list[str],
) -> tuple[str, str]:
    try:
        process.wait(timeout=1)
    except subprocess.TimeoutExpired:
        _terminate_process_group(process, grace_sec=1)
        process.wait(timeout=1)
    for thread in reader_threads:
        thread.join(timeout=1)
    return "".join(stdout_chunks), "".join(stderr_chunks)


def _terminate_process_group(process: subprocess.Popen[str], grace_sec: float = 5.0) -> None:
    descendant_pids = _descendant_pids(process.pid)
    _signal_process(process, signal.SIGTERM)
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
    _signal_pids(descendant_pids, signal.SIGTERM)
    deadline = time.monotonic() + grace_sec
    while time.monotonic() < deadline:
        if process.poll() is not None and not _any_pid_running(descendant_pids):
            return
        time.sleep(0.1)
    _signal_process(process, signal.SIGKILL)
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    _signal_pids(descendant_pids, signal.SIGKILL)


def _signal_process(process: subprocess.Popen[str], sig: signal.Signals) -> None:
    try:
        process.send_signal(sig)
    except ProcessLookupError:
        return


def _signal_pids(pids: set[int], sig: signal.Signals) -> None:
    for pid in sorted(pids, reverse=True):
        try:
            os.kill(pid, sig)
        except ProcessLookupError:
            continue


def _any_pid_running(pids: set[int]) -> bool:
    return any(_pid_running(pid) for pid in pids)


def _pid_running(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    return True


def _descendant_pids(root_pid: int) -> set[int]:
    try:
        result = subprocess.run(
            ["ps", "-o", "pid=,ppid=", "-ax"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.SubprocessError):
        return set()

    children_by_parent: dict[int, list[int]] = {}
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) != 2:
            continue
        try:
            pid = int(parts[0])
            ppid = int(parts[1])
        except ValueError:
            continue
        children_by_parent.setdefault(ppid, []).append(pid)

    descendants: set[int] = set()
    stack = list(children_by_parent.get(root_pid, []))
    while stack:
        pid = stack.pop()
        if pid in descendants:
            continue
        descendants.add(pid)
        stack.extend(children_by_parent.get(pid, []))
    return descendants
