from __future__ import annotations

import os
import signal
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from .base import current_cancel_check, RunnerCancelled


@dataclass(frozen=True)
class CommandResult:
    stdout: str
    stderr: str
    returncode: int
    pid: int


def run_cancellable_command(
    command: Sequence[str],
    cwd: str | Path,
    timeout_sec: int,
    label: str,
    poll_interval: float = 0.25,
) -> CommandResult:
    """Run a CLI subprocess and terminate its process group on cancellation.

    Production note: this is intentionally command-list based. consensusd never
    exposes arbitrary shell execution to agents; callers provide fixed runner
    commands from settings and prompts generated by the orchestrator.
    """

    process = subprocess.Popen(
        list(command),
        cwd=str(cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
    )
    print(f"[consensusd] {label} pid={process.pid}", flush=True)
    deadline = time.monotonic() + timeout_sec
    cancel_check = current_cancel_check()

    while process.poll() is None:
        if cancel_check and cancel_check():
            _terminate_process_group(process)
            stdout, stderr = process.communicate()
            raise RunnerCancelled(
                f"{label} cancelled; terminated pid={process.pid}; "
                f"stdout_tail={stdout[-1000:]!r}; stderr_tail={stderr[-1000:]!r}"
            )
        if time.monotonic() >= deadline:
            _terminate_process_group(process)
            stdout, stderr = process.communicate()
            raise TimeoutError(
                f"{label} timed out after {timeout_sec}s; pid={process.pid}; "
                f"stdout_tail={stdout[-1000:]!r}; stderr_tail={stderr[-1000:]!r}"
            )
        time.sleep(poll_interval)

    stdout, stderr = process.communicate()
    return CommandResult(stdout=stdout, stderr=stderr, returncode=process.returncode, pid=process.pid)


def _terminate_process_group(process: subprocess.Popen[str], grace_sec: float = 5.0) -> None:
    if process.poll() is not None:
        return
    _signal_process(process, signal.SIGTERM)
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
    deadline = time.monotonic() + grace_sec
    while process.poll() is None and time.monotonic() < deadline:
        time.sleep(0.1)
    if process.poll() is not None:
        return
    _signal_process(process, signal.SIGKILL)
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        return


def _signal_process(process: subprocess.Popen[str], sig: signal.Signals) -> None:
    try:
        process.send_signal(sig)
    except ProcessLookupError:
        return
